---
all:
  children:
    frontend:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
          vars:
            internal_alb_dns: "{{ lookup('env', 'INTERNAL_ALB_DNS') }}"
            ecr_frontend_image: "{{ lookup('env', 'ECR_FRONTEND_IMAGE') }}"
            client_name: "{{ lookup('env', 'CLIENT_NAME') }}"
            client_environment: "{{ lookup('env', 'CLIENT_ENVIRONMENT') }}"
    
    backend:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
          vars:
            ecr_backend_image: "{{ lookup('env', 'ECR_BACKEND_IMAGE') }}"
            client_name: "{{ lookup('env', 'CLIENT_NAME') }}"
            client_environment: "{{ lookup('env', 'CLIENT_ENVIRONMENT') }}"
