---
all:
  children:
    frontend:
      hosts:
        frontend-node:
          ansible_connection: local
          ansible_user: ec2-user
    
    backend:
      hosts:
        backend-node:
          ansible_connection: local
          ansible_user: ec2-user
