name: Sync Ansible Folder to S3

on:
  push:
    branches:
      - '*'          # Run for all branches
    paths:
      - 'ansible/**' # Only run if ansible folder changes

jobs:
  sync:
    name: Sync Ansible to S3
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: us-east-1
      S3_PREFIX: ansible

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/githubActionRoleForFiftyfive
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Branch Name
        run: echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Sync Ansible Folder to S3 (Branch Specific)
        run: |
          echo "Syncing to branch folder: $BRANCH_NAME"
          aws s3 sync ansible/ \
            s3://${{ secrets.S3_BUCKET_NAME }}/${{ env.S3_PREFIX }}/$BRANCH_NAME/ \
            --delete
